### ISSUE TITLE
[ Refactor ] 모바일 반응형 너비 적용

### ISSUE THREAD

**Issue by youtheyeon** [SOPT-all/35-COLLABORATION-WEB-MCDONALD#48]
### ♻️ Issue

375px로 고정시켜놓았던 너비를 모바일 반응형으로 수정합니다.

### 🔢 리팩토링하는 이슈를 기입해주세요.

.

### 📝 To-do

- [ ] 글로벌 스타일에서 body 너비 수정
- [ ] 모든 페이지에서 반응형 제대로 적용되는지 확인
- [ ] 사이드 바 너비 수정
